#!/bin/bash

# ================================================
# SNMP Configuration Script
# ================================================
# This script installs and configures SNMP on CentOS/RHEL/AlmaLinux
# ================================================

# Color definitions for beautiful output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color
BOLD='\033[1m'

# Function to print section headers
print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${WHITE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}\n"
}

# Function to print success messages
print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

# Function to print info messages
print_info() {
    echo -e "${CYAN}ℹ️  $1${NC}"
}

# Function to print warning messages
print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

# Function to print error messages
print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Function to print progress messages
print_progress() {
    echo -e "${PURPLE}➜ $1${NC}"
}

# Clear screen for better presentation
clear

# Display script banner
echo -e "${BLUE}┌─────────────────────────────────────────────────────────────┐${NC}"
echo -e "${BLUE}│${WHITE}                 SNMP CONFIGURATION SCRIPT                    ${BLUE}│${NC}"
echo -e "${BLUE}├─────────────────────────────────────────────────────────────┤${NC}"
echo -e "${BLUE}│${CYAN}  This script will install and configure SNMP with custom      ${BLUE}│${NC}"
echo -e "${BLUE}│${CYAN}  extensions for server monitoring                             ${BLUE}│${NC}"
echo -e "${BLUE}└─────────────────────────────────────────────────────────────┘${NC}\n"

# Check if script is run as root
if [[ $EUID -ne 0 ]]; then
    print_error "This script must be run as root"
    exit 1
fi

# Check OS compatibility
if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    print_info "Operating System: $NAME $VERSION"
else
    print_warning "Could not determine OS version"
fi

# Step 1: Install SNMP packages
print_header "STEP 1: Installing SNMP Packages"
print_progress "Installing net-snmp and net-snmp-utils..."
if dnf install -y net-snmp net-snmp-utils > /dev/null 2>&1; then
    print_success "SNMP packages installed successfully"
else
    print_error "Failed to install SNMP packages"
    exit 1
fi

# Step 2: Enable and start SNMP service
print_header "STEP 2: Starting SNMP Service"
print_progress "Enabling and starting snmpd service..."
if systemctl enable --now snmpd > /dev/null 2>&1; then
    print_success "SNMP service enabled and started"
else
    print_error "Failed to start SNMP service"
    exit 1
fi

# Step 3: Check service status
print_header "STEP 3: Verifying SNMP Service Status"
print_progress "Checking snmpd status..."
if systemctl is-active --quiet snmpd; then
    print_success "SNMP service is running"
    echo -e "\n${WHITE}Service Status:${NC}"
    systemctl status snmpd --no-pager | grep -E "Active:|Loaded:" | sed 's/^/  /'
else
    print_error "SNMP service is not running"
fi

# Step 4: Test SNMP walk
print_header "STEP 4: Testing SNMP Communication"
print_progress "Performing test SNMP walk..."
if snmpwalk -v2c -c public localhost 2>&1 | head -5 > /dev/null; then
    print_success "SNMP walk completed successfully"
    echo -e "\n${WHITE}Sample output (first 5 lines):${NC}"
    snmpwalk -v2c -c public localhost 2>/dev/null | head -5 | while read line; do
        echo -e "  ${CYAN}$line${NC}"
    done
else
    print_warning "SNMP walk test failed - may need configuration"
fi

# Step 5: Backup original configuration
print_header "STEP 5: Backing Up Configuration"
BACKUP_FILE="/etc/snmp/snmpd.conf.backup-$(date +%Y%m%d-%H%M%S)"
if [[ -f /etc/snmp/snmpd.conf ]]; then
    cp /etc/snmp/snmpd.conf "$BACKUP_FILE"
    print_success "Original configuration backed up to: $BACKUP_FILE"
else
    print_info "No existing configuration file found"
fi

# Step 6: Configure SNMP with custom extensions
print_header "STEP 6: Configuring SNMP Extensions"
print_progress "Adding custom configurations to /etc/snmp/snmpd.conf"

# Create new configuration
cat > /etc/snmp/snmpd.conf << 'EOF'
# SNMP Configuration File
# Generated by SNMP Configuration Script
# Date: $(date)

# Access Control
rocommunity ED8TBHDLH24MGVYTNTB2V8KC

# Custom Extensions for Monitoring
extend csf /bin/bash -c "systemctl is-active --quiet lfd && echo 1 || echo 0"
extend imunify /bin/bash -c "systemctl is-active --quiet imunify360 && echo 1 || echo 0"
extend litespeed /bin/bash -c "systemctl is-active --quiet lsws && echo 1 || echo 0"
extend mysqlcpu /bin/bash -c "top -b -n 1 | grep mariadb | awk '{print \$9}' | xargs"
extend mailcon /bin/bash -c "netstat -anp | grep -E ':[0-9]+ +ESTABLISHED' | grep -Ei 'exim|dovecot|imap' | wc -l"
extend totalnetworkcon /bin/bash -c "netstat -tunap | grep -v '*' | wc -l"
extend mailqueue /bin/bash -c "exim -bpc"
extend inode_root /bin/bash -c "df -i / | awk 'NR==2 {print \$5}'"
extend iowait /bin/bash -c "top -b -n 1 | awk '/Cpu/ {print \$10}'"
extend cpusteal /bin/bash -c "top -b -n 1 | awk '/Cpu/ {print \$16}'"
extend cpanel_accounts /bin/bash -c "ls /var/cpanel/users | wc -l"
extend all_accounts /bin/bash -c "awk -F: '{print \$1}' /etc/userdomains | wc -l"
extend suspended_accounts /bin/bash -c "ls /var/cpanel/suspended | wc -l"
extend reseller_accounts /bin/bash -c "awk '{print \$2}' /etc/trueuserowners | sort -u | wc -l"

# System Information
syslocation Unknown
syscontact Root <root@localhost>
EOF

print_success "Configuration file updated successfully"

# Display added extensions
echo -e "\n${WHITE}Added extensions:${NC}"
grep "^extend" /etc/snmp/snmpd.conf | while read line; do
    extension=$(echo "$line" | awk '{print $2}')
    echo -e "  ${GREEN}•${NC} ${YELLOW}$extension${NC}"
done

# Step 7: Restart SNMP service
print_header "STEP 7: Applying Configuration"
print_progress "Restarting snmpd service..."
if systemctl restart snmpd; then
    print_success "SNMP service restarted successfully"
else
    print_error "Failed to restart SNMP service"
    exit 1
fi

# Step 8: Verify configuration
print_header "STEP 8: Verifying Configuration"
sleep 2  # Give service time to restart
if systemctl is-active --quiet snmpd; then
    print_success "SNMP service is running with new configuration"
else
    print_error "SNMP service failed to start with new configuration"
    print_info "Restoring from backup..."
    cp "$BACKUP_FILE" /etc/snmp/snmpd.conf
    systemctl restart snmpd
    exit 1
fi

# Step 9: Test custom extensions
print_header "STEP 9: Testing Custom Extensions"
print_progress "Testing some of the configured extensions..."

# Test a few extensions to verify they work
EXTENSIONS_TO_TEST=("csf" "inode_root" "mailqueue")
for ext in "${EXTENSIONS_TO_TEST[@]}"; do
    result=$(snmpwalk -v2c -c ED8TBHDLH24MGVYTNTB2V8KC localhost NET-SNMP-EXTEND-MIB::nsExtendOutputFull.\"$ext\" 2>/dev/null | grep -o 'STRING:.*' | cut -d':' -f2- | xargs)
    if [[ -n "$result" ]]; then
        print_success "Extension '$ext' returned: ${WHITE}$result${NC}"
    else
        print_warning "Extension '$ext' test failed - may need verification"
    fi
done

# Final summary
print_header "CONFIGURATION COMPLETE"
echo -e "${GREEN}✨ SNMP has been successfully configured with all extensions!${NC}\n"

echo -e "${WHITE}📋 Configuration Summary:${NC}"
echo -e "  ${CYAN}•${NC} Community String: ${YELLOW}ED8TBHDLH24MGVYTNTB2V8KC${NC}"
echo -e "  ${CYAN}•${NC} Configuration File: ${YELLOW}/etc/snmp/snmpd.conf${NC}"
echo -e "  ${CYAN}•${NC} Backup File: ${YELLOW}$BACKUP_FILE${NC}"
echo -e "  ${CYAN}•${NC} Total Extensions: ${YELLOW}$(grep -c "^extend" /etc/snmp/snmpd.conf)${NC}\n"

echo -e "${WHITE}🔧 Useful Commands:${NC}"
echo -e "  ${PURPLE}▶${NC} Test SNMP: ${GREEN}snmpwalk -v2c -c ED8TBHDLH24MGVYTNTB2V8KC localhost${NC}"
echo -e "  ${PURPLE}▶${NC} View config: ${GREEN}nano /etc/snmp/snmpd.conf${NC}"
echo -e "  ${PURPLE}▶${NC} Restart SNMP: ${GREEN}systemctl restart snmpd${NC}"
echo -e "  ${PURPLE}▶${NC} Check status: ${GREEN}systemctl status snmpd${NC}\n"

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}\n"
print_success "Script execution completed successfully!"

# Step 10: Display Hostname and Public IP
print_header "SERVER INFORMATION"

HOSTNAME=$(hostname)
IP=$(curl -s ifconfig.me || echo "Unavailable")

echo -e "${WHITE}🖥 Hostname:${NC} ${YELLOW}$HOSTNAME${NC}"
echo -e "${WHITE}🌐 Public IP:${NC} ${YELLOW}$IP${NC}\n"
